# Generated by Django 3.2 on 2022-09-08 04:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='product.pricing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(default='products/default.jpg', upload_to='thumbnails/')),
                ('likes', models.IntegerField(default=0, help_text='Amount of likes generated')),
                ('product_cost', models.IntegerField(default=0, help_text='Price pay to buy this product')),
                ('product_selling_price', models.IntegerField(default=0, help_text='Price you can sell this product')),
                ('product_margin', models.IntegerField(default=0, help_text='Profit you get from this product')),
                ('product_vimeo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ads_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('ads_links', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(choices=[('united States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('The Netherlands', 'The Netherlands'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('UAE', 'UAE'), ('South Africa', 'South Africa'), ('The Philippines', 'The Philippines'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico')], default='United States', max_length=100)),
                ('kind_ads', models.CharField(choices=[('faceBook', 'FaceBook'), ('instagram', 'Instagram'), ('Tiktok', 'Tiktok')], default='faceBook', help_text='FaceBook, Instagram, tiktok...', max_length=250)),
                ('media_ads', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='Photo', help_text='Video, Photo, both', max_length=250)),
                ('is_faceBook', models.BooleanField(default=False)),
                ('is_instagram', models.BooleanField(default=False)),
                ('is_tiktok', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
    ]
