# Generated by Django 3.2 on 2022-10-21 06:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(default='products/default.jpg', upload_to='thumbnails/')),
                ('image_store', models.ImageField(blank=True, default='products/default.jpg', upload_to='image_store/')),
                ('likes', models.IntegerField(default=0, help_text='Amount of likes generated')),
                ('comment', models.IntegerField(default=0, help_text='Amount of comment generated')),
                ('share', models.IntegerField(default=0, help_text='Amount of share generated')),
                ('shopify_price', models.IntegerField(help_text='Product price from shopify')),
                ('aliexpress_price', models.IntegerField(help_text='Product price from aliexpress')),
                ('price_margin', models.IntegerField(help_text='Profit you get from this product')),
                ('aliexpress_url', models.URLField(blank=True)),
                ('product_vimeo_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('countries', models.CharField(choices=[('united States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('The Netherlands', 'The Netherlands'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('UAE', 'UAE'), ('South Africa', 'South Africa'), ('The Philippines', 'The Philippines'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico')], default='United States', max_length=100)),
                ('ads_type', models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='Video', max_length=250)),
                ('media_type', models.CharField(choices=[('faceBook', 'FaceBook'), ('instagram', 'Instagram'), ('Tiktok', 'Tiktok')], default='video', max_length=250)),
                ('gender', models.CharField(choices=[('male or Female', 'Male or Female'), ('male', 'Male'), ('female', 'Female')], default='Male or Female', max_length=250)),
                ('technology', models.CharField(choices=[('shopify', 'Shopify'), ('wooCommerce', 'WooCommerce'), ('cart functionality', 'Cart Functionality'), ('magento', 'magento'), ('salesforce commerce cloud', 'Salesforce Commerce Cloud'), ('prestashop', 'PrestaShop'), ('vtex', 'VTEX'), ('bigcommerce', 'Bigcommerce'), ('ibm websphere commerce', 'IBM Websphere Commerce'), ('sap commerce cloud', 'SAP Commerce Cloud'), ('shopware', 'Shopware'), ('shoptet', 'Shoptet'), ('opencart', 'OpenCart'), ('nopcommerce', 'nopcommerce'), ('oracle commerce', 'Oracle Commerce'), ('intershop', 'Intershop'), ('hybris', 'Hybris'), ('zen cart', 'Zen Cart'), ('oracle commerce cloud', 'Oracle Commerce Cloud'), ('lightspeed ecom', 'Lightspeed eCom'), ('epages', 'EPages'), ('cloudcart', 'CloudCart'), ('kajabi', 'Kajabi'), ('loja integrada', 'Loja Integrada'), ('oxid eshop', 'OXID eShop'), ('riskified', 'Riskified'), ('x-cart', 'X-Cart'), ('commerce server', 'Commerce Server'), ('drupal commerce', 'Drupal Commerce'), ('oscommerce', 'osCommerce'), ('91app', '91App'), ('nuvemshop', 'Nuvemshop'), ('mycashflow', 'Mycashflow'), ('ticimax', 'Ticimax'), ('ecwid', 'Ecwid'), ('gambio', 'Gambio'), ('craft commerce', 'Craft Commerce'), ('ideasoft', 'Ideasoft'), ('ceres', 'Ceres'), ('t-soft', 'T-Soft'), ('storeden', 'Storeden'), ('vtex integrated store', 'VTEX Integrated Store'), ('ccv shop', 'CCV Shop'), ('big cartel', 'Big Cartel'), ('miva', 'Miva'), ('irroba', 'Irroba'), ('volusion', 'Volusion'), ('yepcomm', 'Yepcomm'), ('xtcommerce', 'xtCommerce'), ('ec-cube', 'EC-CUBE')], default='Shopify', max_length=250)),
                ('language', models.CharField(choices=[('english', 'English'), ('armenian', 'Armenian'), ('belarusian', 'Belarusian'), ('bengali', 'Bengali'), ('bosnia', 'Bosnia'), ('bulgarian', 'Bulgarian'), ('bumese', 'Bumese'), ('catalan', 'Catalan'), ('central Kurdish', 'Central Kurdish'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('french', 'French'), ('georgian', 'Georgian'), ('german', 'German'), ('gujarati', 'Gujarati'), ('haitian', 'Haitian'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('javanese', 'Javanese'), ('kannada', 'Kannada'), ('kazakh', 'Kazakh'), ('khmer', 'Khmer'), ('korean', 'Korean'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('maithili', 'Maithili'), ('malay', 'Malay'), ('malayalam', 'Malayalam'), ('mandarin Chinese', 'Mandarin Chinese'), ('marathi', 'Marathi'), ('modern Greek', 'Modern Greek'), ('nepali', 'Nepali'), ('north Azerbaijani', 'North Azerbaijani'), ('northern Uzbek', 'Northern Uzbek'), ('norwegian bokmål', 'Norwegian bokmål'), ('norwegian Nynorsk', 'Norwegian Nynorsk'), ('oriya', 'Oriya'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('Serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('somali', 'Somali'), ('spanish', 'Spanish'), ('sudanese', 'Sudanese'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('tagalog', 'Tagalog'), ('tajik', 'Tajik'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('thai', 'Thai'), ('tibetan', 'Tibetan'), ('turkish', 'Turkish'), ('turkmen', 'Turkmen'), ('uighur', 'Uighur'), ('ukrainian', 'Ukrainian'), ('urdu', 'Urdu'), ('vietnamese', 'Vietnamese')], default='English', max_length=250)),
                ('button', models.CharField(choices=[('buy now', 'Buy Now'), ('shop now', 'Shop Now'), ('learn more', 'Learn More'), ('sign up', 'Sign Up'), ('send message', 'Send Message'), ('book now', 'Book Now'), ('install now', 'Install Now'), ('get directions', 'Get Directions'), ('watch more', 'Watch More'), ('view', 'View'), ('apply now', 'Apply Now'), ('like this page', 'Like This Page'), ('download', 'Download'), ('get offer', 'Get Offer'), ('get tickets', 'Get Tickets'), ('play game', 'Play Game'), ('try it', 'Try It'), ('contact us', 'Contact Us'), ('send whatsapp message', 'Send Whatsapp Message'), ('get quote', 'Get Quote'), ('call now', 'Call Now'), ('donate now', 'Donate Now'), ('buy tickets', 'Buy Tickets'), ('listen now', 'Listen Now'), ('subscribe', 'Subscribe'), ('get show times', 'Get Show Times'), ('view event', 'View Event'), ('see menu', 'See Menu'), ('read', 'Read'), ('use app', 'Use App'), ('order now', 'Order Now'), ('request time', 'Request Time'), ('join', 'Join'), ('open link', 'Open Link'), ('start order', 'Start Order'), ('install app', 'Install App'), ('get your code', 'Get Your Code'), ('see more', 'See More'), ('play now', 'Play Now'), ('see details', 'See Details'), ('open camera', 'Open Camera'), ('sell now', 'Sell Now'), ('buy', 'Buy'), ('about this website', 'About This Website'), ('messsage', 'Messsage'), ('follow', 'Follow'), ('try it', 'Try it'), ('like page', 'Like Page'), ('donate', 'Donate'), ('watch video', 'Watch Video'), ('visit website', 'Visit Website'), ('register now', 'Register Now'), ('email now', 'Email Now'), ('use offer', 'Use Offer'), ('add to profil', 'Add To Profil'), ('turn on', 'Turn On'), ('invite friends', 'Invite Friends'), ('see more', 'see more'), ('visit instagram profile', 'Visit Instagram Profile'), ('go live', 'go live'), ('add to cart', 'Add To Cart'), ('vote now', 'Vote Now'), ('intrested', 'Intrested'), ('see all events', 'See All Events'), ('save', 'Save'), ('search', 'Search'), ('remind me', 'Remind Me'), ('watch yours', 'Watch Yours'), ('save offer', 'Save Offer'), ('get deal', 'Get Deal'), ('get reminded', 'Get Reminded'), ('book test drive', 'Book Test Drive'), ('call', 'Call')], max_length=250)),
                ('store_name', models.CharField(blank=True, help_text='store or ads name', max_length=500, null=True)),
                ('links_to_ads', models.CharField(help_text='A link that will take to ads', max_length=500)),
                ('links_to_a_single_store', models.CharField(help_text='A link that will take to a single the store', max_length=500)),
                ('text_that_comes_with_ads', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('links_to_others_stores', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A link that will take to the store', null=True)),
                ('links_to_others_suppliers', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('is_faceBook', models.BooleanField(default=False)),
                ('is_instagram', models.BooleanField(default=False)),
                ('is_tiktok', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vimeo_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='product.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='product.pricing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun')], max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, help_text='ads like range', null=True)),
                ('name', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun')], default='Jan', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_number', models.IntegerField(blank=True, help_text='ads gender number group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Unkwon', 'Unknown')], default='Female', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_number', models.IntegerField(blank=True, help_text='ads country number group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('New Zealand', 'New Zealand'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('The Netherlands', 'The Netherlands'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('South Korea', 'South Korea'), ('Switzerland', 'Switzerland'), ('Belgium', 'Belgium'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('France', 'France'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('UAE', 'UAE'), ('South Africa', 'South Africa'), ('The Philippines', 'The Philippines'), ('Japan', 'Japan'), ('Singapore', 'Singapore'), ('Argentina', 'Argentina'), ('Mexico', 'Mexico')], default='United States', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text='ads age group range', null=True)),
                ('name', models.CharField(blank=True, choices=[('13-17', '13-17'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65+', '65+')], default='25-34', max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
