# Generated by Django 3.2 on 2023-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='store_domaine_url',
            field=models.CharField(max_length=1100, unique=True),
        ),
    ]
