# Generated by Django 3.2 on 2022-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_type_name',
            new_name='technology',
        ),
        migrations.AddField(
            model_name='product',
            name='ads_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='faceBook', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='social_media_name',
            field=models.CharField(choices=[('faceBook', 'FaceBook'), ('instagram', 'Instagram'), ('Tiktok', 'Tiktok')], default='video', max_length=250),
        ),
    ]
