# Generated by Django 3.2 on 2022-12-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='products/defaut_image_store_light_blue_bag.jpg', upload_to='thumbnails/'),
        ),
    ]
