# Generated by Django 3.2 on 2023-01-07 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEPT', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], default='JAN', max_length=4)),
                ('total_number_of_sale', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
