# Generated by Django 3.2 on 2022-09-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_age_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='site_type',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='Video', max_length=250),
        ),
    ]
