# Generated by Django 3.2 on 2023-01-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230107_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='month_name',
        ),
    ]
