# Generated by Django 3.2 on 2022-12-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221210_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='links_to_a_single_store',
            field=models.CharField(blank=True, help_text='A link that will take to a single the store', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='links_to_ads',
            field=models.CharField(blank=True, help_text='A link that will take to ads', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_margin',
            field=models.IntegerField(blank=True, help_text='Profit you get from this product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_price',
            field=models.IntegerField(blank=True, help_text='Product price from shopify', null=True),
        ),
    ]
