# Generated by Django 3.2 on 2022-11-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221112_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aliexpress_order',
            field=models.IntegerField(default=0, help_text='Amount of aliexpress order generated'),
        ),
    ]
