# Generated by Django 3.2 on 2023-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_sale_month_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_margin',
            field=models.IntegerField(blank=True, default=0, help_text='Profit you get from this product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_price',
            field=models.IntegerField(blank=True, default=0, help_text='Product price from shopify', null=True),
        ),
    ]
