# Generated by Django 3.2 on 2022-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_store',
            field=models.ImageField(default='products/default.jpg', upload_to='image_store/'),
        ),
    ]
