# Generated by Django 3.2 on 2022-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220913_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share',
            field=models.IntegerField(default=0, help_text='Amount of share generated'),
        ),
    ]
