# Generated by Django 3.2 on 2022-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='links_ads',
            field=models.CharField(choices=[('faceBook', 'FaceBook'), ('instagram', 'Instagram'), ('Tiktok', 'Tiktok')], default='#', help_text='A link that will take to the store', max_length=250),
        ),
    ]
