# Generated by Django 3.2 on 2022-09-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
