# Generated by Django 3.2 on 2023-01-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230109_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_margin',
            field=models.FloatField(blank=True, default=0, help_text='Profit you get from this product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_price',
            field=models.FloatField(blank=True, default=0, help_text='Product price from shopify', null=True),
        ),
    ]
