# Generated by Django 3.2 on 2023-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20230109_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aliexpress_price',
            field=models.IntegerField(default=0, help_text='Product price from aliexpress'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_margin',
            field=models.IntegerField(blank=True, default=0, help_text='Profit you get from this product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopify_price',
            field=models.IntegerField(blank=True, default=0, help_text='Product price from shopify', null=True),
        ),
    ]
