# Generated by Django 3.2 on 2022-11-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_number_of_store_selling'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_suppliers_selling',
            field=models.IntegerField(default=0, help_text='Amount of suppliers selling the product'),
        ),
    ]
