# Generated by Django 3.2 on 2022-09-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
