# Generated by Django 3.2 on 2022-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_links_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_faceBook',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_instagram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_tiktok',
        ),
        migrations.RemoveField(
            model_name='product',
            name='media_ads',
        ),
        migrations.AlterField(
            model_name='product',
            name='ads_links',
            field=models.CharField(default='#', help_text='A link that will take to the store', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='links_ads',
            field=models.CharField(default='#', help_text='A link that will take to the store', max_length=250),
        ),
    ]
