# Generated by Django 3.2 on 2022-09-09 05:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220908_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ads_text',
            new_name='links_to_others_suppliers',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='suppliers_links',
            new_name='text_that_comes_with_ads',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ads_links',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kind_ads',
        ),
        migrations.RemoveField(
            model_name='product',
            name='links_ads',
        ),
        migrations.AddField(
            model_name='product',
            name='button',
            field=models.CharField(choices=[('learn more', 'Learn More'), ('shop now', 'Shop Now'), ('sign up', 'Sign Up'), ('send message', 'Send Message'), ('book now', 'Book Now'), ('install now', 'Install Now'), ('get directions', 'Get Directions'), ('watch more', 'Watch More'), ('view', 'View'), ('apply now', 'Apply Now'), ('like this page', 'like this page'), ('download', 'download'), ('get offer', 'get offer'), ('get tickets', 'get tickets'), ('play game', 'play game'), ('try it', 'try it'), ('contact us', 'contact us'), ('send whatsapp message', 'send whatsapp message'), ('get quote', 'get quote'), ('call now', 'call now'), ('donate now', 'donate now'), ('buy tickets', 'buy tickets'), ('listen now', 'listen now'), ('subscribe', 'subscribe'), ('get showtimes', 'get showtimes'), ('view event', 'view event'), ('buy now', 'buy now'), ('see menu', 'see menu'), ('read', 'read'), ('use app', 'use app'), ('order now', 'order now'), ('request time', 'request time'), ('join', 'join'), ('open link', 'open link'), ('start order', 'start order'), ('install app', 'install app'), ('get your code', 'get your code'), ('see more', 'see more'), ('play now', 'Play Now'), ('see details', 'See Details'), ('open camera', 'Open Camera'), ('sell now', 'Sell Now'), ('buy', 'Buy'), ('about this website', 'About This Website'), ('messsage', 'Messsage'), ('follow', 'Follow'), ('try it', 'Try it'), ('like page', 'Like Page'), ('donate', 'Donate'), ('watch video', 'Watch Video'), ('visit website', 'Visit Website'), ('register now', 'Register Now'), ('email now', 'Email Now'), ('use offer', 'Use Offer'), ('add to profil', 'Add To Profil'), ('turn on', 'Turn On'), ('invite friends', 'Invite Friends'), ('see more', 'see more'), ('visit instagram profile', 'Visit Instagram Profile'), ('go live', 'go live'), ('add to cart', 'Add To Cart'), ('vote now', 'Vote Now'), ('intrested', 'Intrested'), ('see all events', 'See All Events'), ('save', 'Save'), ('search', 'Search'), ('remind me', 'Remind Me'), ('watch yours', 'Watch Yours'), ('save offer', 'Save Offer'), ('get deal', 'Get Deal'), ('get reminded', 'Get Reminded'), ('book test drive', 'Book Test Drive'), ('call', 'Call')], default='Shop Now', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male or Female', 'Male or Female'), ('male', 'Male'), ('female', 'Female')], default='Male or Female', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='is_faceBook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tiktok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='language_the_ads',
            field=models.CharField(choices=[('armenian', 'Armenian'), ('belarusian', 'Belarusian'), ('bengali', 'Bengali'), ('bosnia', 'Bosnia'), ('bulgarian', 'Bulgarian'), ('bumese', 'Bumese'), ('catalan', 'Catalan'), ('central Kurdish', 'Central Kurdish'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('english', 'English'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('french', 'French'), ('georgian', 'Georgian'), ('german', 'German'), ('gujarati', 'Gujarati'), ('haitian', 'Haitian'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('javanese', 'Javanese'), ('kannada', 'Kannada'), ('kazakh', 'Kazakh'), ('khmer', 'Khmer'), ('korean', 'Korean'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('maithili', 'Maithili'), ('malay', 'Malay'), ('malayalam', 'Malayalam'), ('mandarin Chinese', 'Mandarin Chinese'), ('marathi', 'Marathi'), ('modern Greek', 'Modern Greek'), ('nepali', 'Nepali'), ('north Azerbaijani', 'North Azerbaijani'), ('northern Uzbek', 'Northern Uzbek'), ('norwegian bokmål', 'Norwegian bokmål'), ('norwegian Nynorsk', 'Norwegian Nynorsk'), ('oriya', 'Oriya'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('Serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('somali', 'Somali'), ('spanish', 'Spanish'), ('sudanese', 'Sudanese'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('tagalog', 'Tagalog'), ('tajik', 'Tajik'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('thai', 'Thai'), ('tibetan', 'Tibetan'), ('turkish', 'Turkish'), ('turkmen', 'Turkmen'), ('uighur', 'Uighur'), ('ukrainian', 'Ukrainian'), ('urdu', 'Urdu'), ('vietnamese', 'Vietnamese')], default='faceBook', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='links_to_a_single_ads',
            field=models.CharField(default='#', help_text='A link that will take to the store', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='links_to_a_single_store',
            field=models.CharField(default='#', help_text='A link that will take to the store', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='links_to_others_stores',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='#', help_text='A link that will take to the store', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_type_name',
            field=models.CharField(choices=[('video', 'Video'), ('photo', 'Photo'), ('both', 'Both')], default='faceBook', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='social_media_name',
            field=models.CharField(choices=[('faceBook', 'FaceBook'), ('instagram', 'Instagram'), ('Tiktok', 'Tiktok')], default='faceBook', max_length=250),
        ),
    ]
