# Generated by Django 3.2 on 2022-09-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220916_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_number', models.IntegerField(blank=True, help_text='ads gender number group range', null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='product.product')),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='title',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_number',
            field=models.IntegerField(blank=True, help_text='ads country number group range', null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
