# Generated by Django 3.2 on 2022-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220909_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='language_the_ads',
            field=models.CharField(choices=[('english', 'English'), ('armenian', 'Armenian'), ('belarusian', 'Belarusian'), ('bengali', 'Bengali'), ('bosnia', 'Bosnia'), ('bulgarian', 'Bulgarian'), ('bumese', 'Bumese'), ('catalan', 'Catalan'), ('central Kurdish', 'Central Kurdish'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('french', 'French'), ('georgian', 'Georgian'), ('german', 'German'), ('gujarati', 'Gujarati'), ('haitian', 'Haitian'), ('hebrew', 'Hebrew'), ('hindi', 'Hindi'), ('hungarian', 'Hungarian'), ('indonesian', 'Indonesian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('javanese', 'Javanese'), ('kannada', 'Kannada'), ('kazakh', 'Kazakh'), ('khmer', 'Khmer'), ('korean', 'Korean'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('maithili', 'Maithili'), ('malay', 'Malay'), ('malayalam', 'Malayalam'), ('mandarin Chinese', 'Mandarin Chinese'), ('marathi', 'Marathi'), ('modern Greek', 'Modern Greek'), ('nepali', 'Nepali'), ('north Azerbaijani', 'North Azerbaijani'), ('northern Uzbek', 'Northern Uzbek'), ('norwegian bokmål', 'Norwegian bokmål'), ('norwegian Nynorsk', 'Norwegian Nynorsk'), ('oriya', 'Oriya'), ('persian', 'Persian'), ('polish', 'Polish'), ('portuguese', 'Portuguese'), ('romanian', 'Romanian'), ('russian', 'Russian'), ('Serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('somali', 'Somali'), ('spanish', 'Spanish'), ('sudanese', 'Sudanese'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('tagalog', 'Tagalog'), ('tajik', 'Tajik'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('thai', 'Thai'), ('tibetan', 'Tibetan'), ('turkish', 'Turkish'), ('turkmen', 'Turkmen'), ('uighur', 'Uighur'), ('ukrainian', 'Ukrainian'), ('urdu', 'Urdu'), ('vietnamese', 'Vietnamese')], default='English', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_type_name',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('wooCommerce', 'WooCommerce'), ('cart functionality', 'Cart Functionality'), ('magento', 'magento'), ('salesforce commerce cloud', 'Salesforce Commerce Cloud'), ('prestashop', 'PrestaShop'), ('vtex', 'VTEX'), ('bigcommerce', 'Bigcommerce'), ('ibm websphere commerce', 'IBM Websphere Commerce'), ('sap commerce cloud', 'SAP Commerce Cloud'), ('shopware', 'Shopware'), ('shoptet', 'Shoptet'), ('opencart', 'OpenCart'), ('nopcommerce', 'nopcommerce'), ('oracle commerce', 'Oracle Commerce'), ('intershop', 'Intershop'), ('hybris', 'Hybris'), ('zen cart', 'Zen Cart'), ('oracle commerce cloud', 'Oracle Commerce Cloud'), ('lightspeed ecom', 'Lightspeed eCom'), ('epages', 'EPages'), ('cloudcart', 'CloudCart'), ('kajabi', 'Kajabi'), ('loja integrada', 'Loja Integrada'), ('oxid eshop', 'OXID eShop'), ('riskified', 'Riskified'), ('x-cart', 'X-Cart'), ('commerce server', 'Commerce Server'), ('drupal commerce', 'Drupal Commerce'), ('oscommerce', 'osCommerce'), ('91app', '91App'), ('nuvemshop', 'Nuvemshop'), ('mycashflow', 'Mycashflow'), ('ticimax', 'Ticimax'), ('ecwid', 'Ecwid'), ('gambio', 'Gambio'), ('craft commerce', 'Craft Commerce'), ('ideasoft', 'Ideasoft'), ('ceres', 'Ceres'), ('t-soft', 'T-Soft'), ('storeden', 'Storeden'), ('vtex integrated store', 'VTEX Integrated Store'), ('ccv shop', 'CCV Shop'), ('big cartel', 'Big Cartel'), ('miva', 'Miva'), ('irroba', 'Irroba'), ('volusion', 'Volusion'), ('yepcomm', 'Yepcomm'), ('xtcommerce', 'xtCommerce'), ('ec-cube', 'EC-CUBE')], default='Shopify', max_length=250),
        ),
    ]
