# Generated by Django 3.2 on 2022-09-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
