# Generated by Django 3.2 on 2022-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220909_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='links_to_a_single_store',
        ),
        migrations.AddField(
            model_name='product',
            name='store_name',
            field=models.CharField(blank=True, help_text='store or ads name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='button',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='links_to_a_single_ads',
            field=models.CharField(default='#', help_text='A link that will take to a single the store', max_length=500),
        ),
    ]
