# Generated by Django 3.2 on 2022-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220909_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('art', 'Art'), ('automobliles & motorcycles', 'Automobliles & Motorcycles'), ('beauty & health', 'Beauty & Health'), ('camping & hiking', 'Camping & Hiking'), ('cellphones & telecommunications', 'Cellphones & Telecommunications'), ('computer & office', 'Computer & Office'), ('consumer electronics', 'Consumer Electronics'), ('festive & party suppliers', 'Festive & Party Suppliers'), ('home & garden', 'Home & Garden'), ('home improvement', 'Home Improvement'), ('jewelry & accessories', 'Jewelry & Accessories'), ('lights & lighting', 'Lights & Lighting'), ('luggage & bags', 'luggage & bags'), ("men's clothing & acccessories", "Men's Clothing & Acccessories"), ('mother & kids', 'Mother & Kids'), ('novelty & special use', 'Novelty & Special Use'), ('office & school supplies', 'Office & School Supplies'), ('pet products', 'Pet Products'), ('phones & telecommunications', 'Phones & Telecommunications'), ('security & protection', 'Security & Protection'), ('shoes', 'Shoes'), ('sports & entertainment', 'Sports & Entertainment'), ('toys & hobbies', 'Toys & Hobbies'), ('watches', 'Watches'), ("women's clothing & accessories", "Women's Clothing & Accessories"), ("women's shoes", "Women's Shoes"), ('general', 'General'), ('gaming', 'Gaming'), ('kitchen', 'Kitchen'), ('sewing', 'Sewing'), ('health', 'Health'), ('gifts', 'Gifts'), ('travel', 'Travel'), ('fishing', 'Fishing'), ('furniture', 'Furniture'), ('christmas', 'Christmas'), ('DIY', 'DIY'), ('baby', 'Baby'), ('wood working', 'Wood Working'), ('power tools', 'Power Tools'), ('hardware tools', 'Hardware Tools')], max_length=100),
        ),
    ]
