# Generated by Django 3.2 on 2022-09-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='links_to_a_single_ads',
            new_name='links_to_a_single_store',
        ),
        migrations.AddField(
            model_name='product',
            name='links_to_ads',
            field=models.CharField(default='#', help_text='A link that will take to ads', max_length=500),
        ),
    ]
