# Generated by Django 3.2 on 2022-09-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220910_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='general', on_delete=django.db.models.deletion.PROTECT, to='product.category'),
        ),
    ]
